// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: service.proto

package service

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	message "unary/proto/message"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// UnaryServiceClient is the client API for UnaryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UnaryServiceClient interface {
	GetProduct(ctx context.Context, in *message.Request, opts ...grpc.CallOption) (*message.Response, error)
}

type unaryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUnaryServiceClient(cc grpc.ClientConnInterface) UnaryServiceClient {
	return &unaryServiceClient{cc}
}

func (c *unaryServiceClient) GetProduct(ctx context.Context, in *message.Request, opts ...grpc.CallOption) (*message.Response, error) {
	out := new(message.Response)
	err := c.cc.Invoke(ctx, "/UnaryService/GetProduct", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UnaryServiceServer is the server API for UnaryService service.
// All implementations must embed UnimplementedUnaryServiceServer
// for forward compatibility
type UnaryServiceServer interface {
	GetProduct(context.Context, *message.Request) (*message.Response, error)
	mustEmbedUnimplementedUnaryServiceServer()
}

// UnimplementedUnaryServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUnaryServiceServer struct {
}

func (UnimplementedUnaryServiceServer) GetProduct(context.Context, *message.Request) (*message.Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedUnaryServiceServer) mustEmbedUnimplementedUnaryServiceServer() {}

// UnsafeUnaryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UnaryServiceServer will
// result in compilation errors.
type UnsafeUnaryServiceServer interface {
	mustEmbedUnimplementedUnaryServiceServer()
}

func RegisterUnaryServiceServer(s grpc.ServiceRegistrar, srv UnaryServiceServer) {
	s.RegisterService(&UnaryService_ServiceDesc, srv)
}

func _UnaryService_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(message.Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UnaryServiceServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/UnaryService/GetProduct",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UnaryServiceServer).GetProduct(ctx, req.(*message.Request))
	}
	return interceptor(ctx, in, info, handler)
}

// UnaryService_ServiceDesc is the grpc.ServiceDesc for UnaryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UnaryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "UnaryService",
	HandlerType: (*UnaryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _UnaryService_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}
